// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/clients/{cid}/account/{aid}": {
            "get": {
                "description": "获取指定账户信息",
                "produces": [
                    "application/json"
                ],
                "summary": "获取指定账户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账户",
                        "name": "aid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.GetAccountResp"
                        }
                    },
                    "401": {
                        "description": "授权失败/未授权",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "404": {
                        "description": "账户不存在",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "406": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    }
                }
            }
        },
        "/v1/clients/{cid}/account/{aid}/transfer": {
            "post": {
                "description": "用户指定账户向指定账户转账",
                "produces": [
                    "application/json"
                ],
                "summary": "转账",
                "parameters": [
                    {
                        "description": "转账请求信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.TransferReq"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "cid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户账户ID",
                        "name": "aid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.TransferResp"
                        }
                    },
                    "404": {
                        "description": "账户不存在",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "406": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "451": {
                        "description": "账户余额不足",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    }
                }
            }
        },
        "/v1/login": {
            "post": {
                "description": "用户登录",
                "produces": [
                    "application/json"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "账户及密码",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "401": {
                        "description": "授权失败/未授权",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "404": {
                        "description": "账户不存在",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "406": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    }
                }
            }
        },
        "/v1/logout": {
            "post": {
                "description": "用户登出",
                "produces": [
                    "application/json"
                ],
                "summary": "登出",
                "parameters": [
                    {
                        "description": "账户ID",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.LogoutReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "401": {
                        "description": "授权失败/未授权",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "404": {
                        "description": "账户不存在",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "406": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "$ref": "#/definitions/restapi.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.GetAccountResp": {
            "$ref": "#/definitions/model.Account"
        },
        "controller.LoginReq": {
            "type": "object",
            "required": [
                "email",
                "pwd"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "pwd": {
                    "type": "string"
                }
            }
        },
        "controller.LogoutReq": {
            "type": "object",
            "required": [
                "cid"
            ],
            "properties": {
                "cid": {
                    "type": "integer"
                }
            }
        },
        "controller.TransferReq": {
            "type": "object",
            "required": [
                "from",
                "fromUnit",
                "to",
                "toNum",
                "toUnit"
            ],
            "properties": {
                "from": {
                    "description": "转出方account_id",
                    "type": "string"
                },
                "fromUnit": {
                    "description": "转出方货币单位",
                    "type": "integer"
                },
                "requestId": {
                    "description": "调用方自定义请求ID，可以为空",
                    "type": "string"
                },
                "to": {
                    "description": "转入方account_id",
                    "type": "string"
                },
                "toNum": {
                    "description": "需要转入的货币数量，以转入方货币单位计算",
                    "type": "number"
                },
                "toUnit": {
                    "description": "转入方货币单位",
                    "type": "integer"
                }
            }
        },
        "controller.TransferResp": {
            "type": "object",
            "required": [
                "cost",
                "from",
                "fromUnit",
                "rate",
                "tid",
                "to",
                "toNum",
                "toUnit"
            ],
            "properties": {
                "cost": {
                    "description": "转账消耗金额，货币单位以请求中FromUnit计算",
                    "type": "number"
                },
                "from": {
                    "description": "转出方account_id",
                    "type": "string"
                },
                "fromUnit": {
                    "description": "转出方货币单位",
                    "type": "integer"
                },
                "rate": {
                    "description": "货币换算汇率 1转出方单位货币 = x转入方单位货币",
                    "type": "number"
                },
                "requestId": {
                    "description": "调用方自定义请求ID，可以为空",
                    "type": "string"
                },
                "tid": {
                    "description": "转账ID",
                    "type": "string"
                },
                "to": {
                    "description": "转入方account_id",
                    "type": "string"
                },
                "toNum": {
                    "description": "需要转入的货币数量，以转入方货币单位计算",
                    "type": "number"
                },
                "toUnit": {
                    "description": "转入方货币单位",
                    "type": "integer"
                }
            }
        },
        "model.Account": {
            "type": "object",
            "properties": {
                "accountId": {
                    "description": "账户ID",
                    "type": "string"
                },
                "balance": {
                    "description": "账户余额",
                    "type": "number"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "modifiedAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "uid": {
                    "description": "账户属主ID，同User.ID相同",
                    "type": "integer"
                },
                "unit": {
                    "description": "账户余额货币单位",
                    "type": "integer"
                }
            }
        },
        "restapi.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
